// Status messages for api requests
export enum STATUS_MESSAGES {
  APPLICATION_UPGRADE = "APPLICATION_UPGRADE",
  AUTHORIZED = "AUTHORIZED",
  CITY_REQUIRED = "CITY_REQUIRED",
  CREATED = "CREATED",
  DELETED = "DELETED",
  FORBIDDEN = "FORBIDDEN",
  DATA_LOADED = "DATA_LOADED",
  INVALID_APP_AUTHENTICATION = "INVALID_APP_AUTHENTICATION",
  INVALID_URL_PARAMETER = "INVALID_URL_PARAMETER",
  INVALID_USER_AUTHENTICATION = "INVALID_USER_AUTHENTICATION",
  NO_DATA = "NO_DATA",
  NOT_FOUND = "NOT_FOUND",
  RESOURCE_EXISTS = "RESOURCE_EXISTS",
  STORE_CHANGING_EMPTY_CART_FIRST = "STORE_CHANGING_EMPTY_CART_FIRST",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  UPDATED = "UPDATED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}

export enum LANGUAGES {
  ENGLISH = "en",
  ARABIC = "ar",
}

export enum VARIANT_OPTION_TYPES {
  STRING = "STRING",
  COLOR = "COLOR",
}
